
spring:
  datasource:
    url: jdbc:mysql://101.37.30.70:3306/ssm_crud
    username: root
    password: 3412410
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #监控统计拦截的过滤器 不加监控界面sql无法统计 wall用于防火墙
      filters: stat,wall,log4j,config
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      max-pool-prepared-statement-per-connection-size: 20
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: "/druid/*"
        login-password: 3412410
        login-username: admin
        allow: 101.37.30.70,169.254.197.172,127.0.0.1,10.254.123.9
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
mybatis:
  mapper-locations: classpath:/com/springboot/staffingsystem/mapper/*.xml
  type-aliases-package: com.springboot.staffingsystem.bean
server:
  port: 8080
#mvc:
#  view:
#    prefix: /